'use client';

import { useState, useCallback } from 'react';
import TreeCanvas from '@/components/TreeCanvas';
import type { TreeNode } from '@/types/tree';

export default function ExplorePage() {
  const [passage, setPassage] = useState('');
  const [tree, setTree] = useState<TreeNode | null>(null);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleExplore = useCallback(async () => {
    if (!passage.trim()) {
      setError('Please paste a textbook passage to explore.');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const response = await fetch('/api/explore/start', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ passage: passage.trim() }),
      });

      if (!response.ok) {
        const data = await response.json();
        setError(data.error ?? 'Exploration failed.');
        return;
      }

      const sid = response.headers.get('X-Session-Id');
      if (sid) setSessionId(sid);

      const text = await response.text();

      try {
        const parsed = JSON.parse(text) as {
          branches: Array<{
            branchType: string;
            label: string;
            summary: string;
            bloomLevel: string;
          }>;
        };

        const rootNode: TreeNode = {
          id: 'root',
          label: 'Your Passage',
          children: parsed.branches.map((b, i) => ({
            id: `branch-${i}`,
            label: b.label,
            branchType: b.branchType as TreeNode['branchType'],
            bloomLevel: b.bloomLevel as TreeNode['bloomLevel'],
            summary: b.summary,
          })),
        };

        setTree(rootNode);
      } catch {
        setError('Failed to parse AI response.');
      }
    } catch {
      setError('Connection error. Please try again.');
    } finally {
      setLoading(false);
    }
  }, [passage]);

  return (
    <div className="flex flex-1 flex-col">
      {!tree ? (
        <div className="flex flex-1 items-center justify-center p-4">
          <div className="flex w-full max-w-xl flex-col gap-4">
            <h1 className="text-2xl font-semibold tracking-tight">
              Explore a passage
            </h1>
            <p className="text-sm text-zinc-500 dark:text-zinc-400">
              Paste a textbook passage to discover career paths, deeper topics,
              and connections.
            </p>
            <textarea
              value={passage}
              onChange={(e) => setPassage(e.target.value)}
              placeholder="Paste your textbook passage here..."
              rows={6}
              maxLength={2000}
              className="rounded-md border border-zinc-300 px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-900"
            />
            <div className="flex items-center justify-between">
              <span className="text-xs text-zinc-400">
                {passage.length}/2000 characters
              </span>
              {error && (
                <span className="text-xs text-red-600 dark:text-red-400">
                  {error}
                </span>
              )}
            </div>
            <button
              onClick={handleExplore}
              disabled={loading || !passage.trim()}
              className="min-h-[44px] rounded-md bg-zinc-900 px-3 py-2.5 text-sm font-medium text-white disabled:opacity-50 dark:bg-zinc-100 dark:text-zinc-900"
            >
              {loading ? 'Exploring...' : 'Explore'}
            </button>
          </div>
        </div>
      ) : (
        <div className="flex flex-1 flex-col">
          <div className="flex items-center justify-between border-b border-zinc-200 px-4 py-2 dark:border-zinc-800">
            <div className="flex items-center gap-2">
              <span className="text-sm font-medium">Knowledge Tree</span>
              {sessionId && (
                <span className="text-xs text-zinc-400">
                  Session: {sessionId.slice(0, 8)}...
                </span>
              )}
            </div>
            <button
              onClick={() => {
                setTree(null);
                setPassage('');
                setSessionId(null);
              }}
              className="text-xs text-zinc-500 hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-200"
            >
              New exploration
            </button>
          </div>
          <div className="flex-1">
            <TreeCanvas data={tree} />
          </div>
          <div className="border-t border-zinc-200 px-4 py-2 text-center dark:border-zinc-800">
            <span className="text-xs text-zinc-400">
              Generated by AI — may contain errors. Discuss with your teacher.
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
